# Site
repository: beingmerry/ben-merryman-resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ben Merryman
title: Controls Engineer
email: ben.merryman@gmail.com
website: benmerryman.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: beingmerry
github_username:  beingmerry
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: benjmerryman
linkedin_username: benmerryman
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: @beingmerry
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: KangaBrew
  icon: fas fa-beer
  url: https://kangabrew.benmerryman.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Ben Merryman and I am a controls engineer who recently expanded my skillset with a full-stack software engineering bootcamp. 
  
  I am a motivated and adaptable engineer who has designed, built, tested and integrated the following: 
  
  Industrial and business logic, industrial devices, applications, PCs, networks, and more. 
  
  Driver of innovation and performance. Web technologies evangelist. 
  
  Forges Operational Technology (OT) with Information Technology (IT) in to interfaces and logic that are easy to learn, use, re-use, and expand. 
  
  **Looking for roles in web development, controls, or manufacturing.** Available to start immediately. 
  
  I am most skilled in: <mark>Control Sytems</mark>, <mark>User Interfaces</mark>, <mark>HTML</mark> and <mark>JavaScript</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: KangaBrew
        link: kangabrew.benmerryman.com
        # link_text: Project Website
        additional_links:
          - title:  KangaBrew
            icon: fab fa-github
            url: github.com/beingmerry/KangaBrew
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Let's go visit a couple breweries! But which ones....?
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>JavaScript</mark>, <mark>REST APIs</mark>, <mark>HTML</mark>, and <mark>CSS</mark>.  I still think it is a good example of fun way to learn to code!

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PROCONEX
        link: proconexdirect.com
        link_text: PROCONEX
        sub_title: Control Systems Engineer
        caption: July 2020 - October 2022
        description: | # this will include new lines to allow paragraphs
            - Created comprehensive graphics library for large pharmaceutical client using DeltaV Live (new HTML5 based graphics) covering pumps, motors, valves, batch controls, sanitation timers, and water-for-injection (WFI) interfaces.
            - Built Alarm Real-time Mapping (ARM) application in DeltaV Live using TypeScript code to interact with SQL databases, filter tables of alarms based on selections, to populate a dynamic alarm guide, and to generate a floor plan style map of current alarms. Utilized Plantweb Optics (K-Net) to build responsive, step-by-step, alarm remediation guides for certain alarms.
            - Developed, configured, and documented control modules (CMs), I/O interfaces, graphics, and equipment modules (EMs) in DeltaV v14.3 and DeltaV v14.LTS.
            - Developed logic, graphical interface, alarming, and cross-vendor communications to Rockwell Logix based controllers at a natural gas storage facility serving 500k + customers.
            - Developed new Ethernet/IP (industrial protocol) layer for communicating to Cytiva Wave Rocker cell propagator saving over 200+ hours in re-development and re-certification at a major international pharma company.
            
      - layout: left
        title: DuPont (on contract from HTSE)
        link: Dupont.com
        link_text: PROCONEX
        sub_title: Control Systems Engineer
        caption: July 2020 - October 2022
        description: | # this will include new lines to allow paragraphs
            - Continued to provide support for Dow legacy plants post spin via ABB 800xA troubleshooting, programming, and administration.
            - Coded and remotely supported the installation of custom RS485 communications protocols between Honeywell devices and ABB CI867 modules, and developed gel die temperature control logic at an Extruded Polystyrene Plant (insulation) in Idaho.
            - Coded and supported on-site the installation of Pelletizer Speed Control Code, loss of anti foam alarm system, and level control code for waste brine units at a Methylated Cellulose (Methocel) Plant in Michigan.
            - Remotely developed process control logic utilizing structured text (ST) with ABB 800xA Control Builder M at a methylated cellulose (Methocel) plant in Michigan (80%).
            - Performed on-site project startup support, operator training, and logic tuning and troubleshooting (15% travel)
            - Remotely provided ABB 800xA 6.0 administrative, troubleshooting, and control logic coding support for an extruded polystyrene (XPS) plant in Idaho (5%).
            

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Iowa State University
        caption: 2006 - 2010
        sub_title: BSc Chemical Engineering

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in control systems and software engineering some of my other interests and hobbies are:
      - Snowboarding
      - Gaming (video and board)
      - Reading

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
